; This file was automatically generated by ScriptHubImporter.py
this.HavilarImpHandler.activeImps := New GameObjectStructure(this.HavilarImpHandler,"HashSet", [0x80])
this.HavilarImpHandler.activeImps._CollectionKeyType := "System.Int32"
<<<<<<< Updated upstream
this.HavilarImpHandler.currentOtherImpIndex := New GameObjectStructure(this.HavilarImpHandler,"Int", [0x1d0])
=======
this.HavilarImpHandler.currentOtherImpIndex := New GameObjectStructure(this.HavilarImpHandler,"Int", [0x1b8])
>>>>>>> Stashed changes
this.HavilarImpHandler.summonImpUltimate := New GameObjectStructure(this.HavilarImpHandler,"Int", [0xb0])
this.HavilarImpHandler.summonImpUltimate.internalCooldownTimer := New GameObjectStructure(this.HavilarImpHandler.summonImpUltimate,"Float", [0xb8])
this.HavilarImpHandler.sacrificeImpUltimate := New GameObjectStructure(this.HavilarImpHandler,"Int", [0xb8])
this.HavilarImpHandler.sacrificeImpUltimate.internalCooldownTimer := New GameObjectStructure(this.HavilarImpHandler.sacrificeImpUltimate,"Float", [0xb8])
