; This file was automatically generated by ScriptHubImporter.py
<<<<<<< Updated upstream
global g_ImportsGameVersion64 := 655
global g_ImportsGameVersionPostFix64 := ""
global g_ImportsGameVersionPlatform64 := "EGS"
=======
global g_ImportsGameVersion64 := 596
global g_ImportsGameVersionPostFix64 := ""
>>>>>>> Stashed changes
